name: publish-artifact

on:
  release:
    types: [released]
  workflow_dispatch:
  push:
    branches:
      - fix_publish_workflow
jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: Treeverse signing
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - if: github.event.release
        name: Update version in pom.xml
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false

      - name: Install secret key for signing
        run: |
          cat <(echo -e '${{ secrets.OSSRH_GPG_SECRET_KEY }}') | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Set up Java and Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - run: ls -ltr /home/runner/.gnupg/
      - name: Build and publish package
        shell: 'script --return --quiet --command "bash {0}"'
        run: mvn -DskipTests --no-transfer-progress --batch-mode deploy --activate-profiles sign-artifacts
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
